In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
import plotly.graph_objs as go
from scipy import stats
linkedin = pd.read_csv("linkedin_company.csv",low_memory=False)
linkedin=linkedin.drop(['link','date_added','date_updated','description','website','entity_id','cusip','isin'],axis=1)
linkedin.head()

,dataset_id,as_of_date,company_name,followers_count,employees_on_platform,industry
0,58329,2015-09-14,Goldman Sachs,552254,38124,Investment Banking
1,58329,2015-09-15,Goldman Sachs,552862,38141,Investment Banking
2,58363,2015-09-16,United Technologies,59157,14982,Aviation & Aerospace
3,58366,2015-09-16,Novo Nordisk,336175,26448,Pharmaceuticals
4,58371,2015-09-16,"Lowe's Companies, Inc.",134255,62574,Retail

In [19]:
Now=linkedin[linkedin['as_of_date']>='2018-01-01'].drop_duplicates(subset='dataset_id',keep='last')
y=Now.groupby('industry')['followers_count'].median().sort_values()
x=Now.groupby('industry')['employees_on_platform'].median().sort_values()
data=[go.Scatter(x=x,y=y,mode='markers')]
layout=go.Layout(title='2018 Industry Median Followers Count vs. Employees on Platform Count',
                xaxis=dict(title='Employees_on_Platform Count',range=[0,5000]),
                yaxis=dict(title='Followers Count',range=[0,80000]))
iplot(go.Figure(data=data,layout=layout))